name: Sum Calculator Workflow

on:
  push:
    branches:
      - master

jobs:
  sum_job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code to the runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Call the Sum Calculator Action
      - name: Call Sum Calculator Action
        id: sum_calculator
        uses:  ./.github/actions/sum-calculator
        with:
          num1: 5
          num2: 7

      # Output the result of the sum
      - name: Output the sum result
        run: echo "The sum is ${{ steps.sum_calculator.outputs.sum }}"